# .github/workflows/ai-review-and-autoapprove.yml
name: AI Review & Auto‑Approve via Gemini

on:
  workflow_run:
    workflows: ["dev → main 自動 PR & 自動マージ"]
    types:
      - completed

permissions:
  contents: read
  pull-requests: write

jobs:
  ai-review-and-approve:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: 開いている PR を取得（dev → main）
        id: get_pr
        uses: actions/github-script@v7
        with:
          script: |
            const prs = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "open",
              base: "main",
              head: "dev"
            });

            if (prs.data.length === 0) {
              core.setFailed("dev → main のPRが見つかりませんでした");
            } else {
              core.setOutput("pr_number", prs.data[0].number);
            }

      - name: Gemini にレビューを依頼
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ steps.get_pr.outputs.pr_number }}
          body: "/gemini review"

      - name: Gemini のレビュー完了を待機
        run: sleep 300  # 5分待ち（必要に応じて調整）

      - name: PR を承認
        uses: peter-evans/approve-pull-request@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.get_pr.outputs.pr_number }}
